apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::739275456688:user/eks-cli-user
      username: eks-cli-user
      groups:
        - system:masters
