apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: flask-mongo-app
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  clusterIP: None  # Headless service for direct communication
